---
title: "RWorksheet_prado#3a"
author: "Prado, James Harry U."
date: "2025-10-13"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
LETTERS[1:11]
```

```{r}
LETTERS[seq(1, 25, by = 2)]
```

```{r}
LETTERS[c(1, 5, 9, 15, 21)]
```

```{r}
letters[22:26]
tail(letters, 5)
```

```{r}
letters[15:24]
```

```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
print(city)
```

```{r}
temp <- c(42, 39, 34, 34, 30, 27)
print(temp)
```

```{r}
april_temp_df <- data.frame(city, temp)
print(april_temp_df)
```

```{r}
names(april_temp_df) <- c("City", "Temperature")
print(april_temp_df)
```

```{r}
str(april_temp_df)
```

```{r}
april_temp_df[3:4, ]
```

```{r}
highest_temp_city <- april_temp_df[april_temp_df$Temperature == max(april_temp_df$Temperature), ]
print("City with Highest Temperature:")
print(highest_temp_city)
lowest_temp_city <- april_temp_df[april_temp_df$Temperature == min(april_temp_df$Temperature), ]
print("City with Lowest Temperature:")
print(lowest_temp_city)
```

```{r}
data_vector <- c(1:8, 11:14)
original_matrix <- matrix(data_vector, nrow = 3, ncol = 4)
original_matrix
matrix_b <- original_matrix * 2
matrix_b
original_matrix[2, ]
original_matrix[1:2, 3:4]
# Alternative: original_matrix[c(1, 2), c(3, 4)]
original_matrix[3, c(2, 3)]
original_matrix[, 4]
rownames(matrix_b) <- c("isa", "dalawa", "tatlo")
colnames(matrix_b) <- c("uno", "dos", "tres", "quatro")
matrix_b
dim(original_matrix) <- c(6, 2)
original_matrix
```

```{r}
data_vector <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
repeated_data <- rep(data_vector, each = 2)
three_d_array <- array(repeated_data, dim = c(2, 4, 3))
three_d_array
```

```{r}
##"Your array has three dimensions."
```

```{r}
dim_names <- list(
  row_names = c("a", "b"),
  col_names = c("A", "B", "C", "D"),
  array_names = c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")
)

named_array <- array(repeated_data, dim = c(2, 4, 3), dimnames = dim_names)
named_array
```